### ISSUE TITLE
error on install

### ISSUE THREAD

**Issue by Gerdobilusir** [Gourieff/sd-webui-roop-nsfw#13]
Textual inversion embeddings loaded(4): gmazzeo, ohmyfrick_yogapuss, style-swirlmagic, sums0d
Textual inversion embeddings skipped(1): 21charturnerv2
Model loaded in 6.1s (load weights from disk: 0.8s, create model: 1.1s, apply weights to model: 1.0s, apply half(): 1.3s, move model to device: 1.4s, calculate empty prompt: 0.4s).
*** Error completing request
*** Arguments: ('https://github.com/Gourieff/sd-webui-roop-nsfw.git', ['ads', 'localization', 'installed'], 0) {}
    Traceback (most recent call last):
      File "F:\stable-diffusion-portable-main\modules\call_queue.py", line 55, in f
        res = list(func(*args, **kwargs))
      File "F:\stable-diffusion-portable-main\modules\ui_extensions.py", line 398, in refresh_available_extensions
        available_extensions = json.loads(text)
      File "F:\stable-diffusion-portable-main\python\lib\json\__init__.py", line 346, in loads
        return _default_decoder.decode(s)
      File "F:\stable-diffusion-portable-main\python\lib\json\decoder.py", line 337, in decode
        obj, end = self.raw_decode(s, idx=_w(s, 0).end())
      File "F:\stable-diffusion-portable-main\python\lib\json\decoder.py", line 355, in raw_decode
        raise JSONDecodeError("Expecting value", s, err.value) from None
    json.decoder.JSONDecodeError: Expecting value: line 8 column 1 (char 7)

---
Traceback (most recent call last):
  File "F:\stable-diffusion-portable-main\venv\lib\site-packages\gradio\routes.py", line 422, in run_predict
    output = await app.get_blocks().process_api(
  File "F:\stable-diffusion-portable-main\venv\lib\site-packages\gradio\blocks.py", line 1326, in process_api
    data = self.postprocess_data(fn_index, result["prediction"], state)
  File "F:\stable-diffusion-portable-main\venv\lib\site-packages\gradio\blocks.py", line 1229, in postprocess_data
    self.validate_outputs(fn_index, predictions)  # type: ignore
  File "F:\stable-diffusion-portable-main\venv\lib\site-packages\gradio\blocks.py", line 1204, in validate_outputs
    raise ValueError(
ValueError: An event handler (f) didn't receive enough output values (needed: 5, received: 4).
Wanted outputs:
    [textbox, html, checkboxgroup, html, textbox]
Received outputs:
    [{'__type__': 'generic_update'}, {'__type__': 'generic_update'}, {'__type__': 'generic_update'}, "<div class='error'>JSONDecodeError: Expecting value: line 8 column 1 (char 7)</div>"]

how to fic this?

**Comment by Gerdobilusir** [comment]
I fixed everything above, but now a new problem, I put enable, insert a picture and nothing happens, it gives such a message

*** Error running postprocess_image: F:\stable-diffusion-portable-main\extensions\sd-webui-roop-nsfw\scripts\faceswap.py    Traceback (most recent call last):
      File "F:\stable-diffusion-portable-main\modules\scripts.py", line 514, in postprocess_image
        script.postprocess_image(p, pp, *script_args)
      File "F:\stable-diffusion-portable-main\extensions\sd-webui-roop-nsfw\scripts\faceswap.py", line 206, in postprocess_image
        result: ImageResult = swap_face(
      File "F:\stable-diffusion-portable-main\extensions\sd-webui-roop-nsfw\scripts\swapper.py", line 177, in swap_face
        face_swapper = getFaceSwapModel(model_path)
      File "F:\stable-diffusion-portable-main\extensions\sd-webui-roop-nsfw\scripts\swapper.py", line 59, in getFaceSwapModel
        FS_MODEL = insightface.model_zoo.get_model(model_path, providers=providers)
      File "F:\stable-diffusion-portable-main\venv\lib\site-packages\insightface\model_zoo\model_zoo.py", line 96, in get_model
        model = router.get_model(providers=providers, provider_options=provider_options)
      File "F:\stable-diffusion-portable-main\venv\lib\site-packages\insightface\model_zoo\model_zoo.py", line 40, in get_model
        session = PickableInferenceSession(self.onnx_file, **kwargs)
      File "F:\stable-diffusion-portable-main\venv\lib\site-packages\insightface\model_zoo\model_zoo.py", line 25, in __init__
        super().__init__(model_path, **kwargs)
      File "F:\stable-diffusion-portable-main\venv\lib\site-packages\onnxruntime\capi\onnxruntime_inference_collection.py", line 383, in __init__
        self._create_inference_session(providers, provider_options, disabled_optimizers)
      File "F:\stable-diffusion-portable-main\venv\lib\site-packages\onnxruntime\capi\onnxruntime_inference_collection.py", line 424, in _create_inference_session
        sess = C.InferenceSession(session_options, self._model_path, True, self._read_config_from_model)
    onnxruntime.capi.onnxruntime_pybind11_state.InvalidProtobuf: [ONNXRuntimeError] : 7 : INVALID_PROTOBUF : Load model from F:\stable-diffusion-portable-main\models/roop\inswapper_128.onnx failed:Protobuf parsing failed.

**Comment by Gourieff** [comment]
This error may occur if there's smth wrong with the model file "inswapper_128.onnx"
Try to download it manually from here https://huggingface.co/henryruhs/roop/resolve/main/inswapper_128.onnx
and put it to the "stable-diffusion-webui\models\roop" replacing existing one
