### ISSUE TITLE
insightface failing to import from protobuf?

### ISSUE THREAD

**Issue by simonindelicate** [Gourieff/sd-webui-roop-nsfw#14]
Hate to bother you with this  - but I get this error on loading the webUI and I'm at a loss. Any assistance gatefully received. ty...

2023-07-14 14:35:51,600 - Roop-GE - INFO - Roop-GE v0.2.0
*** Error loading script: swapper.py
    Traceback (most recent call last):
      File "C:\Users\despo\stable-diffusion-webui\modules\scripts.py", line 274, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "C:\Users\despo\stable-diffusion-webui\modules\script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "C:\Users\despo\stable-diffusion-webui\extensions\sd-webui-roop-nsfw\scripts\swapper.py", line 12, in <module>
        import insightface
      File "C:\Users\despo\stable-diffusion-webui\venv\lib\site-packages\insightface\__init__.py", line 16, in <module>
        from . import model_zoo
      File "C:\Users\despo\stable-diffusion-webui\venv\lib\site-packages\insightface\model_zoo\__init__.py", line 1, in <module>
        from .model_zoo import get_model
      File "C:\Users\despo\stable-diffusion-webui\venv\lib\site-packages\insightface\model_zoo\model_zoo.py", line 11, in <module>
        from .arcface_onnx import *
      File "C:\Users\despo\stable-diffusion-webui\venv\lib\site-packages\insightface\model_zoo\arcface_onnx.py", line 10, in <module>
        import onnx
      File "C:\Users\despo\stable-diffusion-webui\venv\lib\site-packages\onnx\__init__.py", line 13, in <module>
        from onnx.external_data_helper import (
      File "C:\Users\despo\stable-diffusion-webui\venv\lib\site-packages\onnx\external_data_helper.py", line 11, in <module>
        from onnx.onnx_pb import AttributeProto, GraphProto, ModelProto, TensorProto
      File "C:\Users\despo\stable-diffusion-webui\venv\lib\site-packages\onnx\onnx_pb.py", line 4, in <module>
        from .onnx_ml_pb2 import *  # noqa
      File "C:\Users\despo\stable-diffusion-webui\venv\lib\site-packages\onnx\onnx_ml_pb2.py", line 5, in <module>
        from google.protobuf.internal import builder as _builder
    ImportError: cannot import name 'builder' from 'google.protobuf.internal' (C:\Users\despo\stable-diffusion-webui\venv\lib\site-packages\google\protobuf\internal\__init__.py)

**Comment by Gourieff** [comment]
Hm... You can try to reinstall protobuf inside your venv:
check in `stable-diffusion-webui\venv\lib\site-packages\` if there any folders with names start from ~ (ex. "~rotobuf"), delete them
and then:
`pip install -U pip`
`pip install protobuf==3.20.3 --force-reinstall`

**Comment by simonindelicate** [comment]
I think I already tried that, will try again.

**Comment by Gourieff** [comment]
This will definitely solve the issue :)
I suppose that smth went wrong during ONNX installation, smth with dependencies
