### ISSUE TITLE
ImportError: Unable to import dependency onnxruntime/ Error loading script: swapper.py

### ISSUE THREAD

**Issue by natalya-painter** [Gourieff/sd-webui-roop-nsfw#15]
Здравствуйте! Пожалуйста, скажите какие шаги я могу предпринять? 

Traceback (most recent call last):
  File "C:\stable-diffusion-webui-master\extensions\sd-webui-roop-nsfw\install.py", line 52, in <module>
    raise e
  File "C:\stable-diffusion-webui-master\extensions\sd-webui-roop-nsfw\install.py", line 37, in <module>
    installed_version = pkg_resources.get_distribution(package_name).version
  File "C:\stable-diffusion-webui-master\venv\lib\site-packages\pkg_resources\__init__.py", line 478, in get_distribution
    dist = get_provider(dist)
  File "C:\stable-diffusion-webui-master\venv\lib\site-packages\pkg_resources\__init__.py", line 354, in get_provider
    return working_set.find(moduleOrReq) or require(str(moduleOrReq))[0]
  File "C:\stable-diffusion-webui-master\venv\lib\site-packages\pkg_resources\__init__.py", line 909, in require
    needed = self.resolve(parse_requirements(requirements))
  File "C:\stable-diffusion-webui-master\venv\lib\site-packages\pkg_resources\__init__.py", line 795, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'onnxruntime' distribution was not found and is required by the application

Restarting UI...
Closing server running on port: 7860
2023-07-16 13:33:49,526 - ControlNet - INFO - ControlNet v1.1.224
Error loading script: faceswap.py
Traceback (most recent call last):
  File "C:\stable-diffusion-webui-master\venv\lib\site-packages\insightface\__init__.py", line 8, in <module>
    import onnxruntime
ModuleNotFoundError: No module named 'onnxruntime'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\stable-diffusion-webui-master\modules\scripts.py", line 263, in load_scripts
    script_module = script_loading.load_module(scriptfile.path)
  File "C:\stable-diffusion-webui-master\modules\script_loading.py", line 10, in load_module
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\stable-diffusion-webui-master\extensions\sd-webui-roop-nsfw\scripts\faceswap.py", line 15, in <module>
    from scripts.swapper import UpscaleOptions, swap_face, ImageResult
  File "C:\stable-diffusion-webui-master\extensions\sd-webui-roop-nsfw\scripts\swapper.py", line 12, in <module>
    import insightface
  File "C:\stable-diffusion-webui-master\venv\lib\site-packages\insightface\__init__.py", line 10, in <module>
    raise ImportError(
ImportError: Unable to import dependency onnxruntime.

2023-07-16 13:33:49,576 - Roop-GE - INFO - Roop-GE v0.2.0
Error loading script: swapper.py
Traceback (most recent call last):
  File "C:\stable-diffusion-webui-master\venv\lib\site-packages\insightface\__init__.py", line 8, in <module>
    import onnxruntime
ModuleNotFoundError: No module named 'onnxruntime'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\stable-diffusion-webui-master\modules\scripts.py", line 263, in load_scripts
    script_module = script_loading.load_module(scriptfile.path)
  File "C:\stable-diffusion-webui-master\modules\script_loading.py", line 10, in load_module
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\stable-diffusion-webui-master\extensions\sd-webui-roop-nsfw\scripts\swapper.py", line 12, in <module>
    import insightface
  File "C:\stable-diffusion-webui-master\venv\lib\site-packages\insightface\__init__.py", line 10, in <module>
    raise ImportError(
ImportError: Unable to import dependency onnxruntime.

Image Browser: ImageReward is not installed, cannot be used.

**Comment by Gourieff** [comment]
> Здравствуйте! Пожалуйста, скажите какие шаги я могу предпринять?

Здравствуйте, можете попробовать остановить sd-webui и запустить снова, если ошибка не исчезнет, то попробуйте следующее:

1. Перейдите в папку `stable-diffusion-webui\venv\Lib\site-packages`
2. Если увидите папки с именами, начинающимся с `~` (например "~rotobuf") - удалите их
3. Перейдите в папку `stable-diffusion-webui\venv\Scripts`
4. Запустите консоль (cmd) для это папки и напишите в консоли `activate`
5. Обновите pip на всякий случай: `pip install -U pip`
6. Затем по порядку:
   - `pip install insightface==0.7.3`
   - `pip install onnxruntime==1.15.0`
   - `pip install opencv-python==4.7.0.72`
   - `pip install diffusers==0.17.1`
   - `pip install tqdm`
7. Напишите `deactivate`, далее можете закрыть консоль и запустить sd-webui, Roop-GE теперь должен инициализироваться без ошибок

**Comment by natalya-painter** [comment]
Спасибо большое!!! второй способ помог!))
Правда возникли непонятки при установки pip install diffusers==0.17.1

Было написано и надеюсь это не повлияет на работу.

ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
image-reward 1.3 requires datasets==2.11.0, which is not installed.
image-reward 1.3 requires accelerate==0.16.0, but you have accelerate 0.18.0 which is incompatible.
image-reward 1.3 requires diffusers==0.16.0, but you have diffusers 0.17.1 which is incompatible.
image-reward 1.3 requires fairscale==0.4.13, but you have fairscale 0.4.4 which is incompatible.
image-reward 1.3 requires huggingface-hub==0.13.4, but you have huggingface-hub 0.15.1 which is incompatible.
image-reward 1.3 requires timm==0.6.13, but you have timm 0.6.7 which is incompatible.
image-reward 1.3 requires transformers==4.27.4, but you have transformers 4.25.1 which is incompatible.
Successfully installed diffusers-0.17.1 importlib-metadata-6.8.0 zipp-3.16.2

Спасибо ещё раз, за ваш труд!!)

**Comment by Gourieff** [comment]
Не переживайте, это не должно повлиять :)
Обращайтесь если что ;)
