### ISSUE TITLE
error "do_restore_first"

### ISSUE THREAD

**Issue by Darknessssenkrad** [Gourieff/sd-webui-roop-nsfw#17]
I'm getting this error
*** Error running postprocess_image: D:\Stable Diffusion\stable-diffusion-webui\extensions\sd-webui-roop-nsfw\scripts\faceswap.py
    Traceback (most recent call last):
      File "D:\Stable Diffusion\stable-diffusion-webui\modules\scripts.py", line 514, in postprocess_image
        script.postprocess_image(p, pp, *script_args)
      File "D:\Stable Diffusion\stable-diffusion-webui\extensions\sd-webui-roop-nsfw\scripts\faceswap.py", line 212, in postprocess_image
        upscale_options=self.upscale_options,
      File "D:\Stable Diffusion\stable-diffusion-webui\extensions\sd-webui-roop-nsfw\scripts\faceswap.py", line 133, in upscale_options
        return UpscaleOptions(
    TypeError: UpscaleOptions.__init__() got an unexpected keyword argument 'do_restore_first'

**Comment by Gourieff** [comment]
Please, read the IIIrd section of Troubleshooting https://github.com/Gourieff/sd-webui-roop-nsfw#troubleshooting
