### ISSUE TITLE
bug cannot import name 'builder' from 'google.protobuf.internal'

### ISSUE THREAD

**Issue by wzgrx** [Gourieff/sd-webui-roop-nsfw#23]
023-07-22 09:26:38,274 - Roop-GE - INFO - Roop-GE v0.2.2
*** Error loading script: swapper.py
    Traceback (most recent call last):
      File "G:\stable-diffusion-webui\modules\scripts.py", line 295, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "G:\stable-diffusion-webui\modules\script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "G:\stable-diffusion-webui\extensions\sd-webui-roop-nsfw\scripts\swapper.py", line 12, in <module>
        import insightface
      File "G:\stable-diffusion-webui\venv\lib\site-packages\insightface\__init__.py", line 16, in <module>
        from . import model_zoo
      File "G:\stable-diffusion-webui\venv\lib\site-packages\insightface\model_zoo\__init__.py", line 1, in <module>
        from .model_zoo import get_model
      File "G:\stable-diffusion-webui\venv\lib\site-packages\insightface\model_zoo\model_zoo.py", line 11, in <module>
        from .arcface_onnx import *
      File "G:\stable-diffusion-webui\venv\lib\site-packages\insightface\model_zoo\arcface_onnx.py", line 10, in <module>
        import onnx
      File "G:\stable-diffusion-webui\venv\lib\site-packages\onnx\__init__.py", line 13, in <module>
        from onnx.external_data_helper import (
      File "G:\stable-diffusion-webui\venv\lib\site-packages\onnx\external_data_helper.py", line 11, in <module>
        from onnx.onnx_pb import AttributeProto, GraphProto, ModelProto, TensorProto
      File "G:\stable-diffusion-webui\venv\lib\site-packages\onnx\onnx_pb.py", line 4, in <module>
        from .onnx_ml_pb2 import *  # noqa
      File "G:\stable-diffusion-webui\venv\lib\site-packages\onnx\onnx_ml_pb2.py", line 5, in <module>
        from google.protobuf.internal import builder as _builder
    ImportError: cannot import name 'builder' from 'google.protobuf.internal' (G:\stable-diffusion-webui\venv\lib\site-packages\google\protobuf\internal\__init__.py)

**Comment by Gourieff** [comment]
Try to reinstall protobuf:
1. Go to the `G:\stable-diffusion-webui\venv\lib\site-packages` and see if there are any folders with names start from "~" (for example "~rotobuf"), delete them
2. Go to the `G:\stable-diffusion-webui\venv\Scripts` run CMD there and type `activate` in your Console
3. Then:
- `python -m pip install -U pip`
- `pip uninstall protobuf`
- `pip install protobuf==3.20.3`

**Comment by windofbnaf** [comment]
> 嘗試重新安裝protobuf：
> 
> 1. 進入查看`G:\stable-diffusion-webui\venv\lib\site-packages`是否有名稱以“~”開頭的文件夾（例如“~rotobuf”），將其刪除
> 2. 轉到`G:\stable-diffusion-webui\venv\Scripts`運行 CMD 並`activate`在控制台中輸入
> 3. 然後：
> 
> * `python -m pip install -U pip`
> * `pip uninstall protobuf`
> * `pip install protobuf==3.20.3`

I changed the version to protobuf==3.20.3, but when I ran webui-user, it automatically upgraded protobuf to a higher version.

**Comment by Gourieff** [comment]
Perhaps there is some other extension that has a higher version of protobuf dependence and sd-webui installs it on startup requirements check
